services:
  keras-dev:
    build: .
    container_name: keras-dev
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./workspace:/workspace
      - ./datasets:/datasets
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /workspace
    tty: true
    shm_size: "16g"
    ports:
      - "8888:8888"   # JupyterLab
      - "6006:6006"   # TensorBoard

